import bodyParser from "body-parser";
import express from "express";
import { router as auth } from "./controllers/auth";
import { router as draw } from "./controllers/draw";
import { router as register } from "./controllers/register";
import { router as ticket } from "./controllers/tikets";
export const app = express();
app.use(express.json());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use("/tickets", ticket);
app.use("/login", auth);
app.use("/register", register);
app.use("/draws", draw);
